- eyeball/Cargo.toml
- eyeball/src/lib.rs
- eyeball/src/observable.rs
- eyeball/src/state.rs
- eyeball/src/subscriber.rs
Unfortunately this is slower with high numbers of subscribers..
```
Running benches/set_a_lot.rs (target/release/deps/set_a_lot-2dbaf3e0f2a29d73)
baseline                time:   [5.8696 µs 5.8888 µs 5.9085 µs]
change: [-3.7699% -2.1971% -0.7397%] (p = 0.00 < 0.05)
Change within noise threshold.
Found 5 outliers among 100 measurements (5.00%)
4 (4.00%) high mild
1 (1.00%) high severe
no_subscribers          time:   [8.9820 µs 8.9964 µs 9.0106 µs]
change: [-19.656% -19.441% -19.200%] (p = 0.00 < 0.05)
Performance has improved.
Found 10 outliers among 100 measurements (10.00%)
1 (1.00%) low mild
5 (5.00%) high mild
4 (4.00%) high severe
one_subscriber          time:   [21.037 µs 21.926 µs 22.849 µs]
change: [-64.838% -61.860% -58.690%] (p = 0.00 < 0.05)
Performance has improved.
Found 2 …
```
> Replace tokio, manage waking subscribers ourselves

- eyeball-im/CHANGELOG.md
- eyeball-im/Cargo.toml
- eyeball-im/src/vector.rs
- eyeball-im/tests/it.rs
> eyeball-im: Switch to imbl

- eyeball-im-util/src/vector/filter.rs
`VectorExt` has been removed. Let's clear the doc'.
> doc(im-util): Remove mentions to `VectorExt`

- eyeball-im-util/Cargo.toml
- eyeball-im-util/src/vector.rs
- eyeball-im-util/src/vector/limit.rs
- eyeball-im-util/tests/it/limit.rs
- eyeball-im-util/tests/it/main.rs
A `VectorDiff` stream adapter that presents a limited view of the
underlying `ObservableVector`s items.
For example, be `S` a `Stream<Item = VectorDiff>`. The `Vector` represented
by `S` can have any length, but one may want to virtually _limit_ this `Vector`
to a certain size. Then this `DynamicLimit` adapter is well appropriated.
The limit is dynamic, i.e. it changes over time based on values that are polled
from another `Stream` (ref. `Self::limit_stream`).
Because the limit is dynamic, an internal buffered vector is kept, so that
the adapter knows which values can be added when the limit is increased, or
when values are removed and new values must be inserted. This fact is important
if the items of the `Vector` have a non-negligeable size.
It's OK to have a limit larger than the …
> feat(util-im): Add a `DynamicLimit` adapter

- eyeball-im-util/CHANGELOG.md
- eyeball-im-util/src/vector.rs
- eyeball-im-util/src/vector/limit.rs
- eyeball-im-util/tests/it/limit.rs
- DynamicLimit => Limit because  the limit can be static
- DynamicLimit::new => Limit::dynamic
- Limit::new for a static limit constructor
- Limit::dynamic_with_initial_limit for starting with a non-empty vector
> im-util: Rename DynamicLimit => Limit and add more constructors

- eyeball-im-util/Cargo.toml
- eyeball-im-util/src/vector.rs
- eyeball-im-util/src/vector/limit.rs
- eyeball-im-util/src/vector/ops.rs
- eyeball-im-util/src/vector/sort.rs
- eyeball-im-util/src/vector/traits.rs
- eyeball-im-util/tests/it/main.rs
- eyeball-im-util/tests/it/sort.rs
`Sort` is `VectorDiff` stream adapter that presents a sorted view of the underlying `ObservableVector` items. A demonstration:
```rust
use eyeball_im::{ObservableVector, VectorDiff};
use eyeball_im_util::vector::VectorObserverExt;
use imbl::vector;
use std::cmp::Ordering;
use stream_assert::{assert_closed, assert_next_eq, assert_pending};
// A comparison function that is used to sort our
// `ObservableVector` values.
fn cmp<T>(left: &T, right: &T) -> Ordering
where
T: Ord,
{
left.cmp(right)
}
// Our vector.
let mut ob = ObservableVector::<char>::new();
let (values, mut sub) = ob.subscribe().sort_by(&cmp);
//                                              ^^^
//                                              | our comparison function
assert!(values.is_empty());
assert_pending!(sub);
// Append …
```
> feat: Implement the `SortBy` stream adapter

- eyeball-im/src/vector.rs
- eyeball-im/tests/it/main.rs
The idea behind this patch is to avoid emitting a `VectorDiff::Clear` when an `ObservableVector` is already empty.
Thoughts?
> fix(im): `ObservableVecto::clear` emits a `VectorDiff::Clear` when necessary

- .github/workflows/ci.yml
- eyeball-im/Cargo.toml
- eyeball-im/src/vector.rs
- eyeball-im/tests/it/main.rs
- eyeball-im/tests/it/serde.rs
This patch adds the `serde` feature, which —when turned on— implements
`serde::Serialize` for `VectorDiff`.
This is a custom `serde::Serialize` implementation because the `derive`
macro cannot be used here, since it requires `T` in `VectorDiff<T>` to
implement `serde::Serialize` and `Clone`. These constraints must not be
present on the `VectorDiff` enum definition.
This patch also adds a test suite: it tests that all `VectorDiff`'s
variants can be serialized to JSON for example.
Note that `VectorDiff` doesn't implement `serde::Deserialize` because
it's not necessary: `eyeball-im` only _emits_ `VectorDiff`s, it cannot
receive them.
> feat(im): Add support for `serde` in `eyeball-im`

- eyeball-im-util/src/vector/sort.rs
- eyeball-im-util/tests/it/sort.rs
In the `SortBy` stream adapter, when the user is applying a `observable_vector.set(…)` that should result in a `Remove` + `Insert`, it sometimes can be optimised into a single `Set`. This happens when the `old_index` and the `new_index` (resp. the sorted index of the value to be updated, and the sorted index of the new value) are equal. But actually, when `old_index` is lower than `new_index`, there is _another_ missed optimisation in one particular context. If `old_index == new_index - 1`, then we are actually updating the same location. Indeed, the code is already making it clear: when `old_index < new_index`, we need to subtract 1 to `new_index` because removing the value at `old_index` is shifting all values at its right, thus 1 must be subtracted to `new_index`. The missed …
> feat(im-util): `SortBy` optimises `Remove` + `Insert` to `Set` in another case

- eyeball/src/lib.rs
The comment says: “If multiple updates have happened without the subscriber being polled, the next poll will skip all but the latest.”, but the code shows a single `Observable::set` followed by two `Subscriber::next`. I would personally expect the opposite.
This patch updates the example to get 2 `Observable::set` and 1 `Subscriber::next`. The rest of the example has been updated to increase the illustration letter.
> doc: Express what the comment says

- eyeball-im-util/tests/it/sort_by.rs
Sorting by `&rev_cmp` is one more indirection than `rev_cmp` and it does the same thing.
> test: Remove a reference when calling `sort_by`

- eyeball/src/state.rs
- eyeball/src/subscriber.rs
- eyeball/src/subscriber/async_lock.rs
There might be more performant solutions, but this fixes the bug and doesn't show huge perf losses.
> Fix race between closing an observable and a subscriber polling

- eyeball/Cargo.toml
- eyeball/tests/it/main.rs
- eyeball/tests/it/shared.rs
- eyeball/tests/it/unique.rs
This required making the `shared::separate_tasks` test less interesting, because I realized it was wrong before: It was relying on the tasks in the tokio `JoinSet` running in order, otherwise the final value being set on the observable (and thus seen by the subscriber) could be a different one from the one we assert equality with.
> Make eyeball tests independent of tokio

- eyeball-im-util/src/vector/limit.rs
This patch precises the view created by `Limit` starts from 0.
This patch also adds missing Markdown formatting in a comment.
> doc: Improve documentation of `Limit`

- eyeball-im-util/src/vector/limit.rs
- eyeball-im/src/vector.rs
This patch improves `VectorDiff::apply` a little bit, and use it to replace `update_buffered_vector` in `Limit`.
> feat: Improve `VectorDiff::apply` and use it more

- eyeball-im-util/CHANGELOG.md
- eyeball-im-util/src/vector.rs
- eyeball-im-util/src/vector/head.rs
- eyeball-im-util/src/vector/ops.rs
- eyeball-im-util/src/vector/traits.rs
- eyeball-im-util/tests/it/head.rs
- eyeball-im-util/tests/it/main.rs
This patch renames the higher-order stream `Limit` to `Head`. It is a reaction to the upcoming https://github.com/jplatte/eyeball/pull/69 where I've initially proposed the name `RLimit`. After a short thinking, I believe renaming `Limit` to `Head` and `RLimit` to `Tail` would be better names.
This patch renames `Limit` to `Head`.
> chore: Rename `Limit` to `Head`

- .github/workflows/ci.yml
- eyeball/src/shared.rs
This patch updates `crates-ci/typos` from 1.16.22 to 1.29.4.
This patch also fixes an existing typo in the code base.
> chore: Update `typos`

- eyeball-im-util/CHANGELOG.md
- eyeball-im-util/src/vector.rs
- eyeball-im-util/src/vector/head.rs
- eyeball-im-util/src/vector/ops.rs
- eyeball-im-util/src/vector/tail.rs
- eyeball-im-util/src/vector/traits.rs
- eyeball-im-util/tests/it/main.rs
- eyeball-im-util/tests/it/tail.rs
This patch adds the `Tail` higher-order stream. Similarly to `Head`,
it computes a limited view of the underlying `ObservableVector`'s
items, however the view starts from the end —instead of the start— of
the `ObservableVector`.
```rust
use eyeball_im::{ObservableVector, VectorDiff};
use eyeball_im_util::vector::VectorObserverExt;
use imbl::vector;
use stream_assert::{assert_closed, assert_next_eq, assert_pending};
// Our vector.
let mut ob = ObservableVector::<char>::new();
let (values, mut sub) = ob.subscribe().tail(3);
assert!(values.is_empty());
assert_pending!(sub);
// Append multiple values.
ob.append(vector!['a', 'b', 'c', 'd']);
// We get a `VectorDiff::Append` with the latest 3 values!
assert_next_eq!(sub, VectorDiff::Append { values: vector!['b', 'c', 'd'] });
// Let's recap …
```
> feat: Add the `Tail` higher-order stream

- .typos.toml
- eyeball-im-util/src/vector.rs
- eyeball-im-util/src/vector/ops.rs
- eyeball-im-util/src/vector/skip.rs
- eyeball-im-util/src/vector/traits.rs
- eyeball-im-util/tests/it/main.rs
- eyeball-im-util/tests/it/skip.rs
This patch adds the `Skip` higher-order stream. Similarly to `Head` or `Tail`, it computes a limited view of the underlying `ObservableVector`'s items. The view starts after count number of values are skipped, until the end. It must not be confused with `Tail` where `Tail` keeps the last values, while `Skip` skips the first values.
```rust
use eyeball_im::{ObservableVector, VectorDiff};
use eyeball_im_util::vector::VectorObserverExt;
use imbl::vector;
use stream_assert::{assert_closed, assert_next_eq, assert_pending};
// Our vector.
let mut ob = ObservableVector::<char>::new();
let (values, mut sub) = ob.subscribe().skip(3);
assert!(values.is_empty());
assert_pending!(sub);
// Append multiple values.
ob.append(vector!['a', 'b', 'c', 'd', 'e']);
// We get a `VectorDiff::Append` with the …
```
> feat: Add the `Skip` higher-order stream

- eyeball-im-util/CHANGELOG.md
This patch fixes a header typo, and adds a missing entry.
> doc(changelog): Fix a typo and add an entry

- .typos.toml
- eyeball-im-util/src/vector/skip.rs
Its only purpose was to be more efficient than Vector::skip, which it no longer is.
> Remove 'skeep' Vector extension method
